/*
    Ophidia Terminal
    Copyright (C) 2012-2021 CMCC Foundation

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef __OPH_WORKFLOW_DEFINE_H
#define __OPH_WORKFLOW_DEFINE_H

#define OPH_WORKFLOW_KV_SEPARATOR	";"
#define OPH_WORKFLOW_KV_SEPARATOR2	"="
#define OPH_WORKFLOW_KV_BRACKET		"[]"

#define OPH_WORKFLOW_MIN_STRING		24
#define OPH_WORKFLOW_BASIC_SIZE		1024
#define OPH_WORKFLOW_MAX_STRING		2048
#define OPH_WORKFLOW_DOT_MAX_LEN	1048576
#define OPH_WORKFLOW_RANK_SIZE		128
#define OPH_WORKFLOW_ROOT_FOLDER	"/"

#define OPH_WORKFLOW_YES		"yes"
#define OPH_WORKFLOW_NO			"no"
#define OPH_WORKFLOW_NOP		"nop"
#define OPH_WORKFLOW_SKIP		"skip"
#define OPH_WORKFLOW_CONTINUE	"continue"
#define OPH_WORKFLOW_BREAK		"break"
#define OPH_WORKFLOW_REPEAT		"repeat"

#define OPH_WORKFLOW_DELETE				"oph_delete"
#define OPH_WORKFLOW_DELETECONTAINER	"oph_deletecontainer"

#define OPH_WORKFLOW_EXIT_ACTION_NOP				0
#define OPH_WORKFLOW_EXIT_ACTION_DELETE				1
#define OPH_WORKFLOW_EXIT_ACTION_DELETECONTAINER	2

#define OPH_WORKFLOW_CLASSIC	"classic"
#define OPH_WORKFLOW_COMPACT	"compact"

#define OPH_OPERATOR_FOR		"oph_for"
#define OPH_OPERATOR_ENDFOR		"oph_endfor"
#define OPH_OPERATOR_IF			"oph_if"
#define OPH_OPERATOR_ELSEIF		"oph_elseif"
#define OPH_OPERATOR_ELSE		"oph_else"
#define OPH_OPERATOR_ENDIF		"oph_endif"
#define OPH_OPERATOR_WAIT		"oph_wait"
#define OPH_OPERATOR_SET		"oph_set"

// Job status
#define OPH_ODB_STATUS_PREFIX ""	// "OPH_STATUS_"
#define OPH_ODB_STATUS_UNKNOWN_STR OPH_ODB_STATUS_PREFIX "UNKNOWN"
#define OPH_ODB_STATUS_PENDING_STR OPH_ODB_STATUS_PREFIX "PENDING"
#define OPH_ODB_STATUS_WAITING_STR OPH_ODB_STATUS_PREFIX "WAITING"
#define OPH_ODB_STATUS_RUNNING_STR OPH_ODB_STATUS_PREFIX "RUNNING"
#define OPH_ODB_STATUS_START_STR OPH_ODB_STATUS_PREFIX "RUNNING"
#define OPH_ODB_STATUS_SET_ENV_STR OPH_ODB_STATUS_PREFIX "SET_ENV"
#define OPH_ODB_STATUS_INIT_STR OPH_ODB_STATUS_PREFIX "INIT"
#define OPH_ODB_STATUS_DISTRIBUTE_STR OPH_ODB_STATUS_PREFIX "DISTRIBUTE"
#define OPH_ODB_STATUS_EXECUTE_STR OPH_ODB_STATUS_PREFIX "EXECUTE"
#define OPH_ODB_STATUS_REDUCE_STR OPH_ODB_STATUS_PREFIX "REDUCE"
#define OPH_ODB_STATUS_DESTROY_STR OPH_ODB_STATUS_PREFIX "DESTROY"
#define OPH_ODB_STATUS_UNSET_ENV_STR OPH_ODB_STATUS_PREFIX "UNSET_ENV"
#define OPH_ODB_STATUS_COMPLETED_STR OPH_ODB_STATUS_PREFIX "COMPLETED"
#define OPH_ODB_STATUS_ERROR_STR OPH_ODB_STATUS_PREFIX "ERROR"
#define OPH_ODB_STATUS_PENDING_ERROR_STR OPH_ODB_STATUS_PREFIX "PENDING_ERROR"
#define OPH_ODB_STATUS_RUNNING_ERROR_STR OPH_ODB_STATUS_PREFIX "RUNNING_ERROR"
#define OPH_ODB_STATUS_START_ERROR_STR OPH_ODB_STATUS_PREFIX "START_ERROR"
#define OPH_ODB_STATUS_SET_ENV_ERROR_STR OPH_ODB_STATUS_PREFIX "SET_ENV_ERROR"
#define OPH_ODB_STATUS_INIT_ERROR_STR OPH_ODB_STATUS_PREFIX "INIT_ERROR"
#define OPH_ODB_STATUS_DISTRIBUTE_ERROR_STR OPH_ODB_STATUS_PREFIX "DISTRIBUTE_ERROR"
#define OPH_ODB_STATUS_EXECUTE_ERROR_STR OPH_ODB_STATUS_PREFIX "EXECUTE_ERROR"
#define OPH_ODB_STATUS_REDUCE_ERROR_STR OPH_ODB_STATUS_PREFIX "REDUCE_ERROR"
#define OPH_ODB_STATUS_DESTROY_ERROR_STR OPH_ODB_STATUS_PREFIX "DESTROY_ERROR"
#define OPH_ODB_STATUS_UNSET_ENV_ERROR_STR OPH_ODB_STATUS_PREFIX "UNSET_ENV_ERROR"
#define OPH_ODB_STATUS_SKIPPED_STR OPH_ODB_STATUS_PREFIX "SKIPPED"
#define OPH_ODB_STATUS_ABORTED_STR OPH_ODB_STATUS_PREFIX "ABORTED"
#define OPH_ODB_STATUS_UNSELECTED_STR OPH_ODB_STATUS_PREFIX "UNSELECTED"
#define OPH_ODB_STATUS_EXPIRED_STR OPH_ODB_STATUS_PREFIX "EXPIRED"

#define OPH_ODB_STATUS_ACTIVE_STR OPH_ODB_STATUS_PREFIX "ACTIVE"
#define OPH_ODB_STATUS_INACTIVE_STR OPH_ODB_STATUS_PREFIX "INACTIVE"

#endif				//__OPH_WORKFLOW_DEFINE_H
